repos:
  -   repo: https://github.com/psf/black
      rev: 19.3b0
      hooks:
        -   id: black
  -   repo: git://github.com/doublify/pre-commit-clang-format
      rev: master
      hooks:
        -   id: clang-format